package kodlamaio.HumanResourceManagementSystem.dataAccess.abstracts;

import kodlamaio.HumanResourceManagementSystem.entities.concretes.JobAdvertisementActivationByEmployee;
import org.springframework.data.jpa.repository.JpaRepository;

public interface JobAdvertisementActivationByEmployeeDao extends JpaRepository<JobAdvertisementActivationByEmployee,Integer> {
}
